name: test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - "1.19.2"

    steps:
      - name: Install Go
        uses: actions/setup-go/@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Checkout code
        uses: actions/checkout/@v3

      - name: Lint
        uses: golangci/golangci-lint-action@v3

      - name: Run test
        run: go test -v
